name: Deploy AppScript Files
on:
  push:
    branches:
      - main
    paths:
      - 'appScript/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install @google/clasp
        run: npm install -g @google/clasp

      - name: Authenticate with Google
        run: |
          echo "${{ secrets.CLASP_TOKEN }}" > ~/.clasprc.json

      - name: Deploy AppScript files
        run: |
          cd appScript
          clasp push
        env:
          CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
